# Generated by Django 2.2.3 on 2020-02-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20190522_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='good',
        ),
        migrations.AddField(
            model_name='user',
            name='identity',
            field=models.CharField(choices=[('用户', '用户'), ('作家', '作家')], default='用户', max_length=64, verbose_name='身份'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pic',
            field=models.ImageField(upload_to='media', verbose_name='书籍图片'),
        ),
    ]
