# Generated by Django 2.2.3 on 2020-02-04 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20200204_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='章节')),
                ('content', models.TextField(verbose_name='内容')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Book', verbose_name='章节')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
            },
        ),
    ]
