# Generated by Django 2.2.3 on 2020-02-04 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
