# Generated by Django 2.2.3 on 2020-02-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_chapter_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
